import type {
  CinemaLocation,
  CinemaShowtime,
  DateFilterOption,
  FaqItem,
  HeroSlide,
  HighlightBadges,
  Movie,
  MovieDetail,
  Offer,
  SelectOption,
} from './types'

export const heroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    title: 'Blockbusters đang hot tuần này',
    description:
      'Suất chiếu IMAX, Dolby Atmos và 4DX đã mở bán. Đặt vé ngay để không bỏ lỡ những bom tấn lớn nhất đầu năm.',
    stats: ['IMAX', 'Dolby Atmos', 'Pre-booking mở'],
    image:
      'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?q=80&w=1600',
  },
  {
    id: 'hero-2',
    title: 'Rạp gần bạn, lịch chiếu realtime',
    description:
      'Cập nhật ghế trống và giá vé theo từng khung giờ. Đặt vé siêu tốc, nhận mã QR ngay trong ứng dụng.',
    stats: ['Realtime seat map', 'M-ticket', 'Ưu đãi ngân hàng'],
    image:
      'https://images.unsplash.com/photo-1517602302552-471fe67acf66?q=80&w=1600',
  },
  {
    id: 'hero-3',
    title: 'Suất chiếu gia đình cuối tuần',
    description:
      'Combo bắp nước tiết kiệm, phim hoạt hình mới và suất chiếu buổi sáng dành riêng cho cả nhà.',
    stats: ['Combo gia đình', 'Suất sáng', 'Giảm 20%'],
    image:
      'https://images.unsplash.com/photo-1468078809804-4c7b3e60a478?q=80&w=1600',
  },
]

export const cinemaLocations: CinemaLocation[] = [
  {
    id: 'hn-cgv-lotte',
    cityKey: 'hanoi',
    name: 'CGV Lotte Center Hanoi',
    imageUrl: 'https://images.unsplash.com/photo-1469321461812-afeb94496b27?q=80&w=1200',
    distanceFromCenterKm: 2.4,
    venueDetails: 'Level 6, Lotte Center Hanoi',
    address: '54 Lieu Giai, Cong Vi, Ba Dinh, Hanoi, Vietnam',
    latitude: 21.033927,
    longitude: 105.812198,
    showtimesId: 'cinema-1',
    amenities: ['Recliner seating', 'Gourmet snacks', 'Free parking'],
    services: ['M-Ticket', 'Food & beverages', 'Cancellation available'],
    experiences: ['Director Box', 'Dolby Atmos'],
  },
  {
    id: 'hn-beta-thanhxuan',
    cityKey: 'hanoi',
    name: 'Beta Cinemas Thanh Xuan',
    imageUrl: 'https://images.unsplash.com/photo-1517602302552-471fe67acf66?q=80&w=1200',
    distanceFromCenterKm: 5.8,
    venueDetails: '5th Floor, Golden Land Building',
    address: '275 Nguyen Trai, Thanh Xuan, Hanoi, Vietnam',
    latitude: 21.004259,
    longitude: 105.815765,
    showtimesId: 'cinema-2',
    amenities: ['Prime seating', 'Dolby Digital', 'Snack kiosks'],
    services: ['M-Ticket', 'F&B', 'Quick booking'],
    experiences: ['Prime', 'Dolby Atmos'],
  },
  {
    id: 'hn-galaxy-nguyentrai',
    cityKey: 'hanoi',
    name: 'Galaxy Nguyen Trai',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=1200',
    distanceFromCenterKm: 4.1,
    venueDetails: 'Basement B1, Mipec Tower',
    address: '229 Tay Son, Dong Da, Hanoi, Vietnam',
    latitude: 21.007209,
    longitude: 105.826979,
    showtimesId: 'cinema-3',
    amenities: ['Recliner', 'Dolby 7.1', 'Wheelchair access'],
    services: ['M-Ticket', 'Snacks', 'Easy cancellation'],
    experiences: ['Recliner', 'Dolby Atmos'],
  },
  {
    id: 'hcm-cgv-landmark81',
    cityKey: 'tphcm',
    name: 'CGV Vincom Landmark 81',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1200',
    distanceFromCenterKm: 3.2,
    venueDetails: 'Floor B1, Vincom Center Landmark 81',
    address: '208 Nguyen Huu Canh, Binh Thanh, Ho Chi Minh City, Vietnam',
    latitude: 10.794162,
    longitude: 106.72134,
    showtimesId: 'cinema-4',
    amenities: ['Budget friendly', 'Snacks combo', 'Parking'],
    services: ['Box office pickup', 'F&B'],
    experiences: ['Standard'],
  },
  {
    id: 'hcm-bhd-bitexco',
    cityKey: 'tphcm',
    name: 'BHD Star Bitexco',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1200',
    distanceFromCenterKm: 0.9,
    venueDetails: 'Floor 3, Bitexco Financial Tower',
    address: '36 Ho Tung Mau, District 1, Ho Chi Minh City, Vietnam',
    latitude: 10.771644,
    longitude: 106.704499,
    amenities: ['Skyline views', 'Dolby Atmos', 'VIP lounge'],
    services: ['Mobile ticket', 'Digital payments', 'Snack combos'],
    experiences: ['Premium', '4DX'],
  },
  {
    id: 'hcm-lotte-govap',
    cityKey: 'tphcm',
    name: 'Lotte Cinema Go Vap',
    imageUrl: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?q=80&w=1200',
    distanceFromCenterKm: 6.7,
    venueDetails: 'Floor 3, Emart Go Vap',
    address: '366 Phan Van Tri, Go Vap, Ho Chi Minh City, Vietnam',
    latitude: 10.83497,
    longitude: 106.684538,
    amenities: ['Family friendly', 'Arcade zone', 'On-site parking'],
    services: ['Mobile ticket', 'Group booking desk'],
    experiences: ['Standard', 'Kids special'],
  },
  {
    id: 'dn-cgv-vincom',
    cityKey: 'danang',
    name: 'CGV Vincom Da Nang',
    imageUrl: 'https://images.unsplash.com/photo-1494130184753-96ce0dccc1bf?q=80&w=1200',
    distanceFromCenterKm: 1.6,
    venueDetails: 'Level 4, Vincom Plaza',
    address: '910A Ngo Quyen, Son Tra, Da Nang, Vietnam',
    latitude: 16.073422,
    longitude: 108.224331,
    amenities: ['Sea view lounge', 'Dolby Atmos', 'Couple seats'],
    services: ['Mobile ticket', 'Snack delivery to seat'],
    experiences: ['IMAX', 'Premium'],
  },
  {
    id: 'dn-lotte-leduan',
    cityKey: 'danang',
    name: 'Lotte Cinema Le Duan',
    imageUrl: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?q=80&w=1200',
    distanceFromCenterKm: 2.1,
    venueDetails: 'Floor 3, Lotte Mart Da Nang',
    address: '6 Le Duan, Hai Chau, Da Nang, Vietnam',
    latitude: 16.072547,
    longitude: 108.222064,
    amenities: ['Shopping mall access', 'Recliner seats', 'Wheelchair friendly'],
    services: ['Self-service kiosks', 'Digital payments'],
    experiences: ['Standard', 'Recliner'],
  },
  {
    id: 'dn-rapgalaxy',
    cityKey: 'danang',
    name: 'Galaxy Da Nang',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200',
    distanceFromCenterKm: 3.5,
    venueDetails: 'Level 2, Vinh Trung Plaza',
    address: '255-257 Hung Vuong, Thanh Khe, Da Nang, Vietnam',
    latitude: 16.068061,
    longitude: 108.209289,
    amenities: ['Student offers', 'Game zone', 'Free Wi-Fi'],
    services: ['Mobile ticket', 'Snack counter', 'Membership perks'],
    experiences: ['Standard', 'Atmos'],
  },
]

export const listingLanguageOptions: SelectOption[] = [
  { value: 'all', label: 'Tất cả ngôn ngữ' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'english', label: 'English' },
  { value: 'tamil', label: 'Tamil' },
  { value: 'telugu', label: 'Telugu' },
]

export const listingFormatOptions: SelectOption[] = [
  { value: 'all', label: 'Mọi định dạng' },
  { value: '2d', label: '2D' },
  { value: '3d', label: '3D' },
  { value: 'imax', label: 'IMAX' },
  { value: '4dx', label: '4DX' },
]

export const listingHighlightBadges: HighlightBadges = {
  trending: {
    color: '#f50',
    text: 'Đang hot',
  },
  exclusive: {
    color: '#722ed1',
    text: 'Suất đặc biệt',
  },
}

export const movieList: Movie[] = [
  {
    id: 'dune-part-two',
    title: 'Dune: Part Two',
    subtitle: 'Sci-Fi | 166 min',
    rating: 4.8,
    votes: 124532,
    certificate: 'PG-13',
    authors: ['Denis Villeneuve', 'Jon Spaihts'],
    languages: ['english', 'vietnamese'],
    formats: ['imax', '4dx', '2d'],
    tags: ['IMAX', 'Dolby Atmos'],
    runtime: '166 min',
    releaseDate: 'Release 01.03.2024',
    image:
      'https://preview.redd.it/kgss183p65t71.jpg?width=640&crop=smart&auto=webp&s=12a42c2a3221f9833b4207186c8554e23ea5d727',
    trending: true,
    detailId: 'dune-part-two',
  },
  {
    id: 'movie-2',
    title: 'Orbit: Mission Beyond',
    subtitle: 'Sci-fi • 142 phút',
    rating: 4.7,
    votes: 13200,
    certificate: 'UA16+',
    authors: ['Leena Patel'],
    languages: ['english', 'hindi'],
    formats: ['imax', '4dx'],
    tags: ['IMAX', '4DX'],
    runtime: '142 phút',
    releaseDate: 'Khởi chiếu 10.02.2025',
    image:
      'https://feeds.abplive.com/onecms/images/uploaded-images/2023/09/30/f402178710aa1cbd38eb0f5e5283a73d169608707045625_original.jpg?impolicy=abp_cdn&imwidth=1200&height=675',
    trending: true,
  },
  {
    id: 'movie-3',
    title: 'The Midnight Chase',
    subtitle: 'Action thriller • 129 phút',
    rating: 4.4,
    votes: 9800,
    certificate: 'A18+',
    authors: ['Marcus Cole', 'Priya Raman'],
    languages: ['english'],
    formats: ['2d'],
    tags: ['16+', 'Action'],
    runtime: '129 phút',
    releaseDate: 'Khởi chiếu 22.02.2025',
    image:
      'https://images.unsplash.com/photo-1517602302552-471fe67acf66?q=80&w=800',
  },
  {
    id: 'movie-4',
    title: 'Paper Planes',
    subtitle: 'Drama • 118 phút',
    rating: 4.2,
    votes: 7600,
    certificate: 'PG13',
    authors: ['Ishaan Roy'],
    languages: ['english', 'hindi'],
    formats: ['2d'],
    tags: ['Drama', 'UA'],
    runtime: '118 phút',
    releaseDate: 'Khởi chiếu 01.02.2025',
    image:
      'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?q=80&w=800',
  },
  {
    id: 'movie-5',
    title: 'Beat Street',
    subtitle: 'Musical • 124 phút',
    rating: 4.3,
    votes: 5400,
    certificate: 'PG',
    authors: ['Alicia Gomez', 'Jordan Lee'],
    languages: ['english'],
    formats: ['2d', '3d'],
    tags: ['Musical', 'PG'],
    runtime: '124 phút',
    releaseDate: 'Khởi chiếu 28.01.2025',
    image:
      'https://images.unsplash.com/photo-1501769214405-5e5ee5125a02?q=80&w=800',
    trending: true,
  },
  {
    id: 'movie-6',
    title: 'Aurora Nights',
    subtitle: 'Romance • 112 phút',
    rating: 4.1,
    votes: 6200,
    certificate: 'UA7+',
    authors: ['Mira Desai'],
    languages: ['english'],
    formats: ['2d'],
    tags: ['Romance', 'PG'],
    runtime: '112 phút',
    releaseDate: 'Khởi chiếu 05.02.2025',
    image:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=800',
  },
  {
    id: 'movie-7',
    title: 'Racing Hearts',
    subtitle: 'Sports drama • 135 phút',
    rating: 4.5,
    votes: 8900,
    certificate: 'UA13+',
    authors: ['Dev Mehta', 'Claire Summers', 'Harish Venkataraman'],
    languages: ['english', 'hindi'],
    formats: ['2d', '4dx'],
    tags: ['4DX', 'Sports'],
    runtime: '135 phút',
    releaseDate: 'Khởi chiếu 18.02.2025',
    image:
      'https://m.media-amazon.com/images/M/MV5BM2Y5NDhhNWEtYmRlNS00ZmQ0LTkzODYtOTZhNjE4NTVkOWQyXkEyXkFqcGc@._V1_.jpg',
  },
  {
    id: 'movie-8',
    title: 'Chainsaw Man: The Movie - Reze Arc',
    subtitle: 'Fantasy • 138 phút',
    rating: 4.8,
    votes: 15400,
    certificate: 'PG16',
    authors: ['Anaya Sethi', 'Lucas Byrne'],
    languages: ['english', 'tamil'],
    formats: ['imax', '3d'],
    tags: ['Fantasy', 'IMAX'],
    runtime: '138 phút',
    releaseDate: 'Khởi chiếu 25.02.2025',
    image:
      'https://cdn.district.in/movies-assets/images/cinema/Chainsaw-Man---The-Movie--Reze-Arc-%20(1)-b69663c0-9ab6-11f0-a697-578ce98bf125.jpg',
  },
    {
    id: 'movie-9',
    title: 'Demon Slayer: Kimetsu no Yaiba - Infinity Castle',
    subtitle: 'Fantasy • 138 phút',
    rating: 4.9,
    votes: 36000,
    certificate: 'PG13',
    authors: ['Haruo Sotozaki'],
    languages: ['english', 'vietnamese'],
    formats: ['imax', '3d'],
    tags: ['Fantasy', 'IMAX'],
    runtime: '138 phút',
    releaseDate: 'Khởi chiếu 25.02.2025',
    image:
      'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer--Kimetsu-no-Yaiba-Infinity-Castle-cover-57c0fbd0-9aa2-11f0-8dc6-ed40ef18c005.jpg',
  },
]

const duneMovieDetail: MovieDetail = {
  id: 'dune-part-two',
  title: 'Dune: Part Two',
  tagline: 'Long live the fighters.',
  certificate: 'PG-13',
  runtime: '2h 46m',
  genres: ['Science Fiction', 'Adventure', 'Action'],
  languages: ['English', 'Vietnamese subtitles'],
  rating: 4.8,
  votes: 124532,
  releaseDate: 'Release 01 Mar 2024',
  poster:
    'https://image.tmdb.org/t/p/w600_and_h900_bestv2/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
  backdrop:
    'https://image.tmdb.org/t/p/original/a7KyFmpac9qh0iAAMzx5k5QIKily.jpg',
  synopsis:
    'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
  experiences: ['IMAX 2D', 'Dolby Atmos', 'Laser Projection'],
  formats: ['IMAX', '4DX', '2D'],
  highlights: [
    'Filmed across the deserts of Abu Dhabi, Jordan, and Budapest on IMAX-certified cameras',
    'Hans Zimmer returns with an expansive score featuring new Fremen chants',
    'Showcases the rise of Paul Atreides as Muad\'Dib and the Fremen uprising',
  ],
  creators: {
    director: 'Denis Villeneuve',
    writers: ['Denis Villeneuve', 'Jon Spaihts'],
    music: 'Hans Zimmer',
  },
  cast: [
    {
      id: 'cast-1',
      name: 'Timothee Chalamet',
      role: 'Paul Atreides',
      avatar:
        'https://image.tmdb.org/t/p/w276_and_h350_face/BE2sdjpgsa2rNTFa66f7uwJrGQ.jpg',
    },
    {
      id: 'cast-2',
      name: 'Zendaya',
      role: 'Chani',
      avatar:
        'https://image.tmdb.org/t/p/w276_and_h350_face/xZUZ9i6vVayjyhR1vRo9kjY3x2o.jpg',
    },
    {
      id: 'cast-3',
      name: 'Rebecca Ferguson',
      role: 'Lady Jessica',
      avatar:
        'https://image.tmdb.org/t/p/w276_and_h350_face/coVYtSOLx6FQhY0X0N12lfR7L6A.jpg',
    },
    {
      id: 'cast-4',
      name: 'Austin Butler',
      role: 'Feyd-Rautha Harkonnen',
      avatar:
        'https://image.tmdb.org/t/p/w276_and_h350_face/8Pn1sCmud2cwODT4oBmQ1g0K1iP.jpg',
    },
  ],
  metrics: [
    { label: 'Audience Score', value: '95%' },
    { label: 'IMDb', value: '8.8/10' },
    { label: 'Rotten Tomatoes', value: '93%' },
  ],
  reviews: [
    {
      id: 'review-empire',
      source: 'Empire',
      rating: 5,
      maxRating: 5,
      author: 'John Nugent',
      snippet:
        'A thunderous, awe-inspiring epic that expands every idea from its predecessor into something truly operatic.',
      url: 'https://www.empireonline.com/movies/reviews/dune-part-two/',
    },
    {
      id: 'review-guardian',
      source: 'The Guardian',
      rating: 5,
      maxRating: 5,
      author: 'Peter Bradshaw',
      snippet:
        'Villeneuve delivers a visually stunning and emotionally gripping blockbuster of rare ambition.',
      url: 'https://www.theguardian.com/film/review/dune-part-two',
    },
    {
      id: 'review-ign',
      source: 'IGN',
      rating: 9,
      maxRating: 10,
      author: 'Tom Jorgensen',
      snippet:
        'A sci-fi juggernaut that balances intimate character work with mesmerizing large-scale spectacle.',
      url: 'https://www.ign.com/articles/dune-part-two-review',
    },
    {
      id: 'review-verge',
      source: 'The Verge',
      rating: 8,
      maxRating: 10,
      author: 'Charles Pulliam-Moore',
      snippet:
        "Part Two doubles down on the mythic weight of Herbert's story without ever losing sight of the human cost.",
      url: 'https://www.theverge.com/2024/02/21/dune-part-two-review',
    },
  ],
  videos: [
    {
      id: 'video-trailer',
      title: 'Official Trailer',
      thumbnail: 'https://img.youtube.com/vi/Way9Dexny3w/hqdefault.jpg',
      duration: '3:02',
      type: 'Trailer',
      embedUrl: 'https://www.youtube.com/embed/Way9Dexny3w',
    },
    {
      id: 'video-featurette',
      title: 'Featurette: Building the Fremen World',
      thumbnail: 'https://img.youtube.com/vi/Z9j1a0SagjA/hqdefault.jpg',
      duration: '4:11',
      type: 'Featurette',
      embedUrl: 'https://www.youtube.com/embed/Z9j1a0SagjA',
    },
  ],
  posters: [
    {
      id: 'poster-1',
      image: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      title: 'Official poster',
    },
    {
      id: 'poster-2',
      image: 'https://image.tmdb.org/t/p/w780/zSWdAEc2EDwR4HP2dTXB7pGwx4j.jpg',
      title: 'Character ensemble',
    },
    {
      id: 'poster-3',
      image: 'https://image.tmdb.org/t/p/w780/eqH2ZcYbP82LPgjeX8E6AG0gFfN.jpg',
      title: 'Paul & Chani',
    },
    {
      id: 'poster-4',
      image: 'https://image.tmdb.org/t/p/w780/5kAGbi9MOPJ19rxv360uA7irXqV.jpg',
      title: 'Fremen uprising',
    },
  ],
}

const demonSlayerDetail: MovieDetail = {
  id: 'movie-9',
  title: 'Demon Slayer: Kimetsu no Yaiba - Infinity Castle',
  tagline: 'Breath deep. Fight harder.',
  certificate: 'PG-13',
  runtime: '2h 15m',
  genres: ['Fantasy', 'Action', 'Animation'],
  languages: ['Japanese', 'English dub', 'Vietnamese subtitles'],
  rating: 4.9,
  votes: 36000,
  releaseDate: 'Release 18 Apr 2025',
  poster:
    'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer--Kimetsu-no-Yaiba-Infinity-Castle-cover-57c0fbd0-9aa2-11f0-8dc6-ed40ef18c005.jpg',
  backdrop:
    'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer--Kimetsu-no-Yaiba-Infinity-Castle-banner-4bc02c00-9aa3-11f0-8dc6-ed40ef18c005.jpg',
  synopsis:
    'Tanjiro, Nezuko, and the Hashira rally for the ultimate confrontation inside Muzan Kibutsuji’s Infinity Castle. Blistering battles, shattered bonds, and breathtaking animation bring the climactic arc of Demon Slayer to life on the big screen.',
  experiences: ['IMAX 3D', 'Dolby Atmos', 'Laser Projection'],
  formats: ['IMAX', '3D', '2D'],
  highlights: [
    'Animated by ufotable with full HDR mastering for theatrical release',
    'Features brand-new sequences expanding on the Infinity Castle arc',
    'Original theme song performed by LiSA with orchestral arrangement',
  ],
  creators: {
    director: 'Haruo Sotozaki',
    writers: ['Koyoharu Gotouge', 'Haruo Sotozaki'],
    music: 'Yuki Kajiura & Go Shiina',
  },
  cast: [
    {
      id: 'cast-ds-1',
      name: 'Natsuki Hanae',
      role: 'Tanjiro Kamado (JP)',
      avatar:
        'https://cdn.district.in/movies-assets/images/cinema/Natsuki-Hanae-avatar-26a32000-9aa4-11f0-8dc6-ed40ef18c005.png',
    },
    {
      id: 'cast-ds-2',
      name: 'Akari Kitō',
      role: 'Nezuko Kamado (JP)',
      avatar:
        'https://cdn.district.in/movies-assets/images/cinema/Akari-Kito-avatar-2a9a7ed0-9aa4-11f0-8dc6-ed40ef18c005.png',
    },
    {
      id: 'cast-ds-3',
      name: 'Zach Aguilar',
      role: 'Tanjiro Kamado (EN)',
      avatar:
        'https://cdn.district.in/movies-assets/images/cinema/Zach-Aguilar-avatar-2e33d720-9aa4-11f0-8dc6-ed40ef18c005.png',
    },
    {
      id: 'cast-ds-4',
      name: 'Anairis Quiñones',
      role: 'Mitsuri Kanroji (EN)',
      avatar:
        'https://cdn.district.in/movies-assets/images/cinema/Anairis-Quinones-avatar-31613470-9aa4-11f0-8dc6-ed40ef18c005.png',
    },
  ],
  metrics: [
    { label: 'Audience Score', value: '97%' },
    { label: 'MyAnimeList', value: '9.3/10' },
    { label: 'Box Office (JP)', value: '¥13.2B' },
  ],
  reviews: [
    {
      id: 'review-anime-news-network',
      source: 'Anime News Network',
      rating: 4.5,
      maxRating: 5,
      author: 'Lynzee Loveridge',
      snippet:
        'Infinity Castle delivers wall-to-wall spectacle while staying anchored to the emotional journeys of the Demon Slayer Corps.',
      url: 'https://www.animenewsnetwork.com/review/demon-slayer-infinity-castle/.205612',
    },
    {
      id: 'review-crunchyroll',
      source: 'Crunchyroll',
      rating: 9,
      maxRating: 10,
      author: 'Joseph Luster',
      snippet:
        'A staggering technical accomplishment that thrusts fans directly into the heart of the series’ climactic saga.',
      url: 'https://www.crunchyroll.com/news/infinity-castle-review',
    },
    {
      id: 'review-ign-anime',
      source: 'IGN Anime',
      rating: 8,
      maxRating: 10,
      author: 'Ari Notis',
      snippet:
        'Occasional pacing issues can’t spoil the jaw-dropping set pieces that make Infinity Castle essential viewing.',
      url: 'https://www.ign.com/articles/demon-slayer-infinity-castle-review',
    },
  ],
  videos: [
    {
      id: 'video-ds-trailer',
      title: 'Official Trailer',
      duration: '02:45',
      type: 'Trailer',
      embedUrl: 'https://www.youtube.com/embed/OdM92ap8_c0',
      thumbnail:
        'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer--Kimetsu-no-Yaiba-Infinity-Castle-cover-57c0fbd0-9aa2-11f0-8dc6-ed40ef18c005.jpg',
    },
    {
      id: 'video-ds-featurette',
      title: 'Behind the Scenes: Infinity Castle',
      duration: '03:20',
      type: 'Featurette',
      embedUrl: 'https://www.youtube.com/embed/SSqP02X7p3g',
      thumbnail:
        'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer-Infinity-Castle-group-poster-60a3cb70-9aa4-11f0-8dc6-ed40ef18c005.jpg',
    },
  ],
  posters: [
    {
      id: 'poster-ds-1',
      image:
        'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer--Kimetsu-no-Yaiba-Infinity-Castle-cover-57c0fbd0-9aa2-11f0-8dc6-ed40ef18c005.jpg',
      title: 'Official poster',
    },
    {
      id: 'poster-ds-2',
      image:
        'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer-Infinity-Castle-group-poster-60a3cb70-9aa4-11f0-8dc6-ed40ef18c005.jpg',
      title: 'Hashira ensemble',
    },
    {
      id: 'poster-ds-3',
      image:
        'https://cdn.district.in/movies-assets/images/cinema/Demon-Slayer-Infinity-Castle-nezuko-63a2ad00-9aa4-11f0-8dc6-ed40ef18c005.jpg',
      title: 'Nezuko spotlight',
    },
  ],
}

export const movieDetail: MovieDetail = duneMovieDetail

export const movieDetailsById: Record<string, MovieDetail> = {
  [duneMovieDetail.id]: duneMovieDetail,
  [demonSlayerDetail.id]: demonSlayerDetail,
}

export const dateOptions: DateFilterOption[] = [
  { value: '2025-03-21', label: 'Fri', meta: '21 Mar' },
  { value: '2025-03-22', label: 'Sat', meta: '22 Mar' },
  { value: '2025-03-23', label: 'Sun', meta: '23 Mar' },
  { value: '2025-03-24', label: 'Mon', meta: '24 Mar' },
  { value: '2025-03-25', label: 'Tue', meta: '25 Mar' },
  { value: '2025-03-26', label: 'Wed', meta: '26 Mar' },
  { value: '2025-03-27', label: 'Thu', meta: '27 Mar' },
]

export const languageFilters: SelectOption[] = [
  { value: 'all', label: 'All languages' },
  { value: 'English', label: 'English' },
  { value: 'Vietnamese', label: 'Vietnamese' },
]

export const formatFilters: SelectOption[] = [
  { value: 'all', label: 'All formats' },
  { value: '2D', label: '2D' },
  { value: 'IMAX', label: 'IMAX' },
  { value: '4DX', label: '4DX' },
]

export const experienceFilters: SelectOption[] = [
  { value: 'all', label: 'Any experience' },
  { value: 'IMAX Laser', label: 'IMAX Laser' },
  { value: 'Dolby Atmos', label: 'Dolby Atmos' },
  { value: '4DX ScreenX', label: '4DX ScreenX' },
  { value: 'Recliner Lounge', label: 'Recliner Lounge' },
]

export const cinemaShowtimes: CinemaShowtime[] = [
  {
    id: 'cinema-1',
    name: 'CGV Lotte Center Hanoi',
    provider: 'CGV',
    address: '54 Lieu Giai, Cong Vi, Ba Dinh, Hanoi',
    distance: '2.4 km',
    amenities: ['IMAX laser projection', 'Gourmet snacks', 'Free parking'],
    experiences: ['IMAX Laser', 'Dolby Atmos'],
    services: ['M-Ticket', 'Reserved seating', 'Refundable shows'],
    cancellationPolicy: 'Free cancellation up to 60 mins before showtime.',
    priceFrom: 'VND 180,000',
    slots: [
      {
        id: 'cinema-1-slot-1',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '10:30 AM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 220,000',
      },
      {
        id: 'cinema-1-slot-2',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '01:45 PM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 220,000',
        isFillingFast: true,
      },
      {
        id: 'cinema-1-slot-3',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '05:30 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 200,000',
      },
      {
        id: 'cinema-1-slot-4',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '08:50 PM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 230,000',
      },
      {
        id: 'cinema-1-slot-5',
        movieId: 'movie-9',
        date: '2025-03-22',
        time: '11:15 AM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'Vietnamese',
        price: 'VND 190,000',
      },
      {
        id: 'cinema-1-slot-6',
        movieId: 'movie-9',
        date: '2025-03-22',
        time: '03:40 PM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 230,000',
      },
      {
        id: 'cinema-1-slot-7',
        movieId: 'movie-9',
        date: '2025-03-23',
        time: '07:05 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 200,000',
        isPrime: true,
      },
    ],
  },
  {
    id: 'cinema-2',
    name: 'Beta Cinemas Thanh Xuan',
    provider: 'Beta',
    address: '275 Nguyen Trai, Thanh Xuan, Hanoi',
    distance: '5.8 km',
    amenities: ['Budget combos', 'Student discounts', 'Arcade zone'],
    experiences: ['Recliner Lounge', 'Dolby Atmos'],
    services: ['M-Ticket', 'In-seat dining', 'Refundable shows'],
    priceFrom: 'VND 120,000',
    slots: [
      {
        id: 'cinema-2-slot-1',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '09:50 AM',
        experience: 'Recliner Lounge',
        format: '2D',
        language: 'Vietnamese',
        price: 'VND 145,000',
      },
      {
        id: 'cinema-2-slot-2',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '01:20 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 160,000',
      },
      {
        id: 'cinema-2-slot-3',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '04:45 PM',
        experience: 'Recliner Lounge',
        format: '2D',
        language: 'English',
        price: 'VND 150,000',
        isFillingFast: true,
      },
      {
        id: 'cinema-2-slot-4',
        movieId: 'movie-9',
        date: '2025-03-22',
        time: '07:30 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 165,000',
      },
      {
        id: 'cinema-2-slot-5',
        movieId: 'dune-part-two',
        date: '2025-03-23',
        time: '10:10 AM',
        experience: 'Recliner Lounge',
        format: '2D',
        language: 'Vietnamese',
        price: 'VND 140,000',
      },
    ],
  },
  {
    id: 'cinema-3',
    name: 'Galaxy Nguyen Trai',
    provider: 'Galaxy',
    address: '229 Tay Son, Dong Da, Hanoi',
    distance: '4.1 km',
    amenities: ['Free Wi-Fi', 'Snack kiosks', 'Digital payment'],
    experiences: ['4DX ScreenX', 'Dolby Atmos'],
    services: ['M-Ticket', 'Quick pickup', 'Refundable shows'],
    priceFrom: 'VND 150,000',
    slots: [
      {
        id: 'cinema-3-slot-1',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '11:00 AM',
        experience: '4DX ScreenX',
        format: '4DX',
        language: 'English',
        price: 'VND 260,000',
      },
      {
        id: 'cinema-3-slot-2',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '02:30 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 200,000',
      },
      {
        id: 'cinema-3-slot-3',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '06:10 PM',
        experience: '4DX ScreenX',
        format: '4DX',
        language: 'English',
        price: 'VND 260,000',
        isFillingFast: true,
      },
      {
        id: 'cinema-3-slot-4',
        movieId: 'movie-9',
        date: '2025-03-22',
        time: '09:40 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'Vietnamese',
        price: 'VND 195,000',
      },
      {
        id: 'cinema-3-slot-5',
        movieId: 'movie-9',
        date: '2025-03-23',
        time: '01:15 PM',
        experience: 'Dolby Atmos',
        format: '2D',
        language: 'English',
        price: 'VND 200,000',
      },
    ],
  },
  {
    id: 'cinema-4',
    name: 'CGV Vincom Landmark 81',
    provider: 'CGV',
    address: '208 Nguyen Huu Canh, Binh Thanh, Ho Chi Minh City',
    distance: '3.2 km',
    amenities: ['Skyline lounge', 'Premium seating', 'Valet parking'],
    experiences: ['IMAX Laser', 'Recliner Lounge'],
    services: ['M-Ticket', 'In-seat dining', 'Premium concierge'],
    priceFrom: 'VND 210,000',
    slots: [
      {
        id: 'cinema-4-slot-1',
        movieId: 'dune-part-two',
        date: '2025-03-21',
        time: '10:15 AM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 250,000',
      },
      {
        id: 'cinema-4-slot-2',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '02:00 PM',
        experience: 'Recliner Lounge',
        format: '2D',
        language: 'Vietnamese',
        price: 'VND 220,000',
      },
      {
        id: 'cinema-4-slot-3',
        movieId: 'movie-9',
        date: '2025-03-21',
        time: '05:45 PM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 260,000',
        isPrime: true,
      },
      {
        id: 'cinema-4-slot-4',
        movieId: 'movie-9',
        date: '2025-03-22',
        time: '09:20 PM',
        experience: 'IMAX Laser',
        format: 'IMAX',
        language: 'English',
        price: 'VND 260,000',
      },
      {
        id: 'cinema-4-slot-5',
        movieId: 'movie-9',
        date: '2025-03-23',
        time: '01:35 PM',
        experience: 'Recliner Lounge',
        format: '2D',
        language: 'English',
        price: 'VND 225,000',
      },
    ],
  },
]

export const offers: Offer[] = [
  {
    id: 'offer-1',
    title: 'Axis Bank Credit Card',
    description: 'Giảm 10% tối đa ₹150 cho hóa đơn từ ₹500 trở lên.',
    badge: 'Bank offer',
    terms: ['Áp dụng 2 lần mỗi cuối tuần', 'Chỉ áp dụng suất chiếu được gắn tag'],
  },
  {
    id: 'offer-2',
    title: 'Paytm Wallet Cashback',
    description: 'Hoàn ₹125 khi đặt từ 2 vé trở lên và thanh toán bằng Paytm.',
    badge: 'Cashback',
    terms: ['Ví phải hoàn tất KYC', 'Hoàn tiền trong vòng 24 giờ'],
  },
  {
    id: 'offer-3',
    title: 'Food Combo Deal',
    description: 'Tiết kiệm 20% combo bắp + nước khi đặt trước.',
    badge: 'Snack deal',
    terms: ['Áp dụng tại PVR, INOX', 'Số lượng có hạn mỗi ngày'],
  },
]

export const faqItems: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'Phim được xếp loại gì?',
    answer:
      'Sunny Sanskari Ki Tulsi Kumari được chứng nhận UA. Khuyến nghị phụ huynh đi cùng trẻ dưới 12 tuổi.',
  },
  {
    id: 'faq-2',
    question: 'Có thể hủy vé không?',
    answer:
      'Bạn có thể hủy ở các rạp hỗ trợ như PVR Director’s Cut và M2K Cinemas. Kiểm tra tag Hủy vé trước khi đặt.',
  },
  {
    id: 'faq-3',
    question: 'Suất chiếu có phụ đề tiếng Anh không?',
    answer:
      'Có, tất cả suất IMAX và Prime đều kèm phụ đề tiếng Anh.',
  },
]
